name: 7.0-GITHUB_OUTPUT-variables
on: 
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step level output
        id: tag1
        run: | 
          echo "Application=swiggy" >> $GITHUB_OUTPUT
          echo "Environment=prod" >> $GITHUB_OUTPUT
      - name: printing above outputs.
        run:  |
          echo "Application is: ${{steps.tag1.outputs.Application}}"
          echo "Environment is: ${{steps.tag1.outputs.Environment}}"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    outputs:
      Application: ${{steps.tag2.outputs.value}}
    steps:
      - name: job level output
        id : tag2
        run: | 
          echo "value=Paytm" >> $GITHUB_OUTPUT
          echo "value=test" >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: printing previous job outputs
        run: |
          echo "Application is: ${{needs.job2.outputs.Application}}"





